### ISSUE TITLE
BMW Component Not Working 

### ISSUE THREAD

**Issue by juan11perez** [ChristianKuehnel/bimmer_connected#32]
Sensor is not loading; this is related to https://github.com/home-assistant/home-assistant/issues/12698
I'm getting the following error log: https://hastebin.com/rirereburi.sql
Please see attached raw data:
[Archive.zip](https://github.com/ChristianKuehnel/bimmer_connected/files/1764325/Archive.zip)

**Comment by ChristianKuehnel** [comment]
Hey @juan11perez,

thx for the data! It's a bit strange: you have an NBTevo head unit (as myself), but you're is reporting fewer attributes than the two other examples of "NBTevo" I've received so far:
* https://github.com/ChristianKuehnel/bimmer_connected/blob/master/test/responses/G31_NBTevo/dynamic.json
* https://github.com/ChristianKuehnel/bimmer_connected/blob/master/test/responses/F87_NBTevo/dynamic.json

Especially you're not getting the fuel-related information, the state of the lids and windows.

So the bug with the missing attributes should be fixed by now. I'll create a bugfix release of the library and then an update for HomeAssistant in the next minutes. That should solve the error message, but it will not give you more data, as you're note getting it from the server...

**Comment by juan11perez** [comment]
@ChristianKuehnel thank you very much for looking into this. I'll contact BMW and ask a few questions. Will revert with their feedback.
